name: auto-pr-develop-to-main

on:
  push:
    branches:
      - develop

concurrency:
  group: auto-pr-develop-to-main
  cancel-in-progress: false

jobs:
  open_or_update_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Open or update PR develop -> main
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = "develop";
            const base = "main";

            const latestMessage =
              context.payload?.head_commit?.message ||
              (Array.isArray(context.payload?.commits) && context.payload.commits.slice(-1)[0]?.message) ||
              `Sync ${head} to ${base}`;

            // Find existing open PR from develop -> main
            const { data: openPRs } = await github.rest.pulls.list({
              owner,
              repo,
              state: "open",
              base,
              head: `${owner}:${head}`,
              per_page: 1,
            });

            if (openPRs.length) {
              const pr = openPRs[0];
              if (pr.title !== latestMessage) {
                await github.rest.pulls.update({
                  owner,
                  repo,
                  pull_number: pr.number,
                  title: latestMessage,
                });
                core.info(`Updated PR #${pr.number} title.`);
              } else {
                core.info(`PR #${pr.number} already has the latest title.`);
              }
              core.setOutput("pr_number", pr.number);
            } else {
              const { data: newPR } = await github.rest.pulls.create({
                owner,
                repo,
                base,
                head,
                title: latestMessage,
                body: "Automated PR to merge `develop` into `main`.",
                maintainer_can_modify: true,
              });
              core.info(`Created PR #${newPR.number}.`);
              core.setOutput("pr_number", newPR.number);
            }